# Generated by Django 5.1.6 on 2025-02-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('location', models.CharField(max_length=255)),
                ('telescope', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('date_taken', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('comment', models.TextField()),
                ('sent_time', models.DateTimeField(editable=False)),
            ],
        ),
    ]
